version: "3.8"

services:
  node:
    image: node:lts-alpine
    container_name: ${PROJECT_NAME}-node
    working_dir: $WORKING_DIR
    networks:
      - microservice
    volumes:
      - ./app:$WORKING_DIR

  nginx:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    networks:
      - microservice
    ports:
      - ${WEBSERVER_PORT}:80
    working_dir: /etc/nginx
    volumes:
      - ./app:$WORKING_DIR
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d:/etc/nginx/conf.d

networks:
  microservice:
    name: microservice
    driver: bridge