version: "3.8"

networks:
  microservice:
    name: microservice
    driver: bridge

services:
  node:
    image: node:lts-alpine
    container_name: ${PROJECT_NAME}-node
    working_dir: $WORKING_DIR
    volumes:
      - ./app:/var/www/html
    command: /bin/sh -c "yarn install && yarn build leasing-app"

  nginx:
    restart: always
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - ${WEBSERVER_PORT}:80
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        USER_NAME: $USER_NAME
        GROUP_NAME: $GROUP_NAME
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
        WORKING_DIR: $WORKING_DIR
    working_dir: /etc/nginx
    volumes:
      - ./app:$WORKING_DIR
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/extra:/etc/nginx/extra
